AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  menu-driver

Parameters:
  Environment:
    Type: String
  SinglePlatformClientID:
    Type: String
  SinglePlatformClientSecret:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        MENUS_TABLE_NAME: !Ref MenusTable
        SP_CLIENT_ID: !Ref 'SinglePlatformClientID'
        SP_CLIENT_SECRET: !Ref 'SinglePlatformClientSecret'

Resources:
  MenusDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda.menus_data
      Runtime: ruby2.5
      Policies: AmazonDynamoDBFullAccess
      Events:
        Data:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /menus_data
            Method: get

  MenusTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join ['-', ['MenuDriver', !Ref 'Environment']]
      PrimaryKey: 
        Name: id
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataApi:
    Description: "API Gateway endpoint URL for Prod stage for menus_data function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/menus_data/"
  MenusDataFunction:
    Description: "menus_data Lambda Function ARN"
    Value: !GetAtt MenusDataFunction.Arn
  DataFunctionIamRole:
    Description: "Implicit IAM Role created for menus_data function"
    Value: !GetAtt MenusDataFunction.Arn
